```{r}
install.packages("ISLR")
library(ISLR)
library(caret)

Hitters <- na.omit(Hitters)

split <- createDataPartition(y=Hitters$Salary, p = 0.5, list = FALSE)
train <- Hitters[split,]
test <- Hitters[-split,]

```


```{r}
set.seed(825) # for reproducing these results
ridge <- train(Salary ~., data = train,
               method='ridge',
               lambda = 4,
               preProcess=c('scale', 'center'))

ridge
```


```{r}
ridge.pred <- predict(ridge, test)

sqrt(mean(ridge.pred - test$Salary)^2)


```

k-folds + cross-validation

```{r}
set.seed(825)
fitControl <- trainControl(method = "cv",
                           number = 10)
# Set seq of lambda to test
lambdaGrid <- expand.grid(lambda = 10^seq(10, -2, length=100))

ridge <- train(Salary~., data = train,
               method='ridge',
               trControl = fitControl,
                tuneGrid = lambdaGrid,
               preProcess=c('center', 'scale')
)

ridge
```


```{r}
predict(ridge$finalModel, type='coef', mode='norm')$coefficients[19,]
```


```{r}
ridge.pred <- predict(ridge, test)
sqrt(mean(ridge.pred - test$Salary)^2)
```


```{r}
lmfit <- train(Salary ~., data = train,
               method='lm',
               trControl = fitControl,
               preProc=c('scale', 'center'))
lmfit
```


```{r}
coef(lmfit$finalModel)
```


```{r}
lmfit.pred <- predict(lmfit, test)
sqrt(mean(lmfit.pred - test$Salary)^2)
```

The Lasso

```{r}
lasso <- train(Salary ~., train,
               method='lasso',
               preProc=c('scale','center'),
               trControl=fitControl)
lasso
```


```{r}
predict.enet(lasso$finalModel, type='coefficients', s=lasso$bestTune$fraction, mode='fraction')
```


```{r}
lasso.pred <- predict(lasso, test)
sqrt(mean(lasso.pred - test$Salary)^2)
```


```{r}
plot(varImp(ridge, scale = FALSE))

plot(varImp(lasso, scale = FALSE))

plot(varImp(lmfit, scale = FALSE))
```




